"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .channel import Channel
    from .contact import Contact, ContactTypedDict
    from .contactupdaterequest import (
        ContactUpdateRequest,
        ContactUpdateRequestTypedDict,
    )
    from .deletesenderop import DeleteSenderRequest, DeleteSenderRequestTypedDict
    from .deletetemplateop import DeleteTemplateRequest, DeleteTemplateRequestTypedDict
    from .getcontactbyphoneop import (
        GetContactByPhoneRequest,
        GetContactByPhoneRequestTypedDict,
    )
    from .getcontactop import GetContactRequest, GetContactRequestTypedDict
    from .getmessageop import GetMessageRequest, GetMessageRequestTypedDict
    from .getsenderop import GetSenderRequest, GetSenderRequestTypedDict
    from .gettemplateop import GetTemplateRequest, GetTemplateRequestTypedDict
    from .listcontactsop import (
        ListContactsRequest,
        ListContactsRequestTypedDict,
        ListContactsResponse,
        ListContactsResponseTypedDict,
    )
    from .listmessagesop import (
        ListMessagesRequest,
        ListMessagesRequestTypedDict,
        ListMessagesResponse,
        ListMessagesResponseTypedDict,
    )
    from .listsendersop import ListSendersResponse, ListSendersResponseTypedDict
    from .listtemplatesop import ListTemplatesResponse, ListTemplatesResponseTypedDict
    from .message import Message, MessageTypedDict
    from .messagecontent import (
        Button,
        ButtonTypedDict,
        MessageContent,
        MessageContentContact,
        MessageContentContactTypedDict,
        MessageContentTypedDict,
        Row,
        RowTypedDict,
        Section,
        SectionTypedDict,
    )
    from .messagerequest import MessageRequest, MessageRequestTypedDict
    from .messageresponse import MessageResponse, MessageResponseTypedDict
    from .messagestatus import MessageStatus
    from .messagetype import MessageType
    from .phoneintrospectionrequest import (
        PhoneIntrospectionRequest,
        PhoneIntrospectionRequestTypedDict,
    )
    from .phoneintrospectionresponse import (
        PhoneIntrospectionResponse,
        PhoneIntrospectionResponseTypedDict,
    )
    from .reactionrequest import ReactionRequest, ReactionRequestTypedDict
    from .security import Security, SecurityTypedDict
    from .sender import Capabilities, CapabilitiesTypedDict, Sender, SenderTypedDict
    from .sendercreaterequest import SenderCreateRequest, SenderCreateRequestTypedDict
    from .senderupdaterequest import SenderUpdateRequest, SenderUpdateRequestTypedDict
    from .sendmessageop import SendMessageRequest, SendMessageRequestTypedDict
    from .sendreactionop import SendReactionRequest, SendReactionRequestTypedDict
    from .template import Status, Template, TemplateTypedDict
    from .templatecreaterequest import (
        TemplateCreateRequest,
        TemplateCreateRequestTypedDict,
    )
    from .updatecontactop import UpdateContactRequest, UpdateContactRequestTypedDict
    from .updatesenderop import UpdateSenderRequest, UpdateSenderRequestTypedDict
    from .whatsappcategory import WhatsAppCategory

__all__ = [
    "Button",
    "ButtonTypedDict",
    "Capabilities",
    "CapabilitiesTypedDict",
    "Channel",
    "Contact",
    "ContactTypedDict",
    "ContactUpdateRequest",
    "ContactUpdateRequestTypedDict",
    "DeleteSenderRequest",
    "DeleteSenderRequestTypedDict",
    "DeleteTemplateRequest",
    "DeleteTemplateRequestTypedDict",
    "GetContactByPhoneRequest",
    "GetContactByPhoneRequestTypedDict",
    "GetContactRequest",
    "GetContactRequestTypedDict",
    "GetMessageRequest",
    "GetMessageRequestTypedDict",
    "GetSenderRequest",
    "GetSenderRequestTypedDict",
    "GetTemplateRequest",
    "GetTemplateRequestTypedDict",
    "ListContactsRequest",
    "ListContactsRequestTypedDict",
    "ListContactsResponse",
    "ListContactsResponseTypedDict",
    "ListMessagesRequest",
    "ListMessagesRequestTypedDict",
    "ListMessagesResponse",
    "ListMessagesResponseTypedDict",
    "ListSendersResponse",
    "ListSendersResponseTypedDict",
    "ListTemplatesResponse",
    "ListTemplatesResponseTypedDict",
    "Message",
    "MessageContent",
    "MessageContentContact",
    "MessageContentContactTypedDict",
    "MessageContentTypedDict",
    "MessageRequest",
    "MessageRequestTypedDict",
    "MessageResponse",
    "MessageResponseTypedDict",
    "MessageStatus",
    "MessageType",
    "MessageTypedDict",
    "PhoneIntrospectionRequest",
    "PhoneIntrospectionRequestTypedDict",
    "PhoneIntrospectionResponse",
    "PhoneIntrospectionResponseTypedDict",
    "ReactionRequest",
    "ReactionRequestTypedDict",
    "Row",
    "RowTypedDict",
    "Section",
    "SectionTypedDict",
    "Security",
    "SecurityTypedDict",
    "SendMessageRequest",
    "SendMessageRequestTypedDict",
    "SendReactionRequest",
    "SendReactionRequestTypedDict",
    "Sender",
    "SenderCreateRequest",
    "SenderCreateRequestTypedDict",
    "SenderTypedDict",
    "SenderUpdateRequest",
    "SenderUpdateRequestTypedDict",
    "Status",
    "Template",
    "TemplateCreateRequest",
    "TemplateCreateRequestTypedDict",
    "TemplateTypedDict",
    "UpdateContactRequest",
    "UpdateContactRequestTypedDict",
    "UpdateSenderRequest",
    "UpdateSenderRequestTypedDict",
    "WhatsAppCategory",
]

_dynamic_imports: dict[str, str] = {
    "Channel": ".channel",
    "Contact": ".contact",
    "ContactTypedDict": ".contact",
    "ContactUpdateRequest": ".contactupdaterequest",
    "ContactUpdateRequestTypedDict": ".contactupdaterequest",
    "DeleteSenderRequest": ".deletesenderop",
    "DeleteSenderRequestTypedDict": ".deletesenderop",
    "DeleteTemplateRequest": ".deletetemplateop",
    "DeleteTemplateRequestTypedDict": ".deletetemplateop",
    "GetContactByPhoneRequest": ".getcontactbyphoneop",
    "GetContactByPhoneRequestTypedDict": ".getcontactbyphoneop",
    "GetContactRequest": ".getcontactop",
    "GetContactRequestTypedDict": ".getcontactop",
    "GetMessageRequest": ".getmessageop",
    "GetMessageRequestTypedDict": ".getmessageop",
    "GetSenderRequest": ".getsenderop",
    "GetSenderRequestTypedDict": ".getsenderop",
    "GetTemplateRequest": ".gettemplateop",
    "GetTemplateRequestTypedDict": ".gettemplateop",
    "ListContactsRequest": ".listcontactsop",
    "ListContactsRequestTypedDict": ".listcontactsop",
    "ListContactsResponse": ".listcontactsop",
    "ListContactsResponseTypedDict": ".listcontactsop",
    "ListMessagesRequest": ".listmessagesop",
    "ListMessagesRequestTypedDict": ".listmessagesop",
    "ListMessagesResponse": ".listmessagesop",
    "ListMessagesResponseTypedDict": ".listmessagesop",
    "ListSendersResponse": ".listsendersop",
    "ListSendersResponseTypedDict": ".listsendersop",
    "ListTemplatesResponse": ".listtemplatesop",
    "ListTemplatesResponseTypedDict": ".listtemplatesop",
    "Message": ".message",
    "MessageTypedDict": ".message",
    "Button": ".messagecontent",
    "ButtonTypedDict": ".messagecontent",
    "MessageContent": ".messagecontent",
    "MessageContentContact": ".messagecontent",
    "MessageContentContactTypedDict": ".messagecontent",
    "MessageContentTypedDict": ".messagecontent",
    "Row": ".messagecontent",
    "RowTypedDict": ".messagecontent",
    "Section": ".messagecontent",
    "SectionTypedDict": ".messagecontent",
    "MessageRequest": ".messagerequest",
    "MessageRequestTypedDict": ".messagerequest",
    "MessageResponse": ".messageresponse",
    "MessageResponseTypedDict": ".messageresponse",
    "MessageStatus": ".messagestatus",
    "MessageType": ".messagetype",
    "PhoneIntrospectionRequest": ".phoneintrospectionrequest",
    "PhoneIntrospectionRequestTypedDict": ".phoneintrospectionrequest",
    "PhoneIntrospectionResponse": ".phoneintrospectionresponse",
    "PhoneIntrospectionResponseTypedDict": ".phoneintrospectionresponse",
    "ReactionRequest": ".reactionrequest",
    "ReactionRequestTypedDict": ".reactionrequest",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Capabilities": ".sender",
    "CapabilitiesTypedDict": ".sender",
    "Sender": ".sender",
    "SenderTypedDict": ".sender",
    "SenderCreateRequest": ".sendercreaterequest",
    "SenderCreateRequestTypedDict": ".sendercreaterequest",
    "SenderUpdateRequest": ".senderupdaterequest",
    "SenderUpdateRequestTypedDict": ".senderupdaterequest",
    "SendMessageRequest": ".sendmessageop",
    "SendMessageRequestTypedDict": ".sendmessageop",
    "SendReactionRequest": ".sendreactionop",
    "SendReactionRequestTypedDict": ".sendreactionop",
    "Status": ".template",
    "Template": ".template",
    "TemplateTypedDict": ".template",
    "TemplateCreateRequest": ".templatecreaterequest",
    "TemplateCreateRequestTypedDict": ".templatecreaterequest",
    "UpdateContactRequest": ".updatecontactop",
    "UpdateContactRequestTypedDict": ".updatecontactop",
    "UpdateSenderRequest": ".updatesenderop",
    "UpdateSenderRequestTypedDict": ".updatesenderop",
    "WhatsAppCategory": ".whatsappcategory",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
