"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class ContactTypedDict(TypedDict):
    id: str
    phone_number: str
    r"""E.164 phone number."""
    country_code: NotRequired[str]
    whatsapp_window_open: NotRequired[bool]
    r"""Whether the 24-hour WhatsApp window is currently open."""
    last_whatsapp_message_at: NotRequired[datetime]
    r"""When the contact last messaged via WhatsApp."""
    metadata: NotRequired[Dict[str, str]]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class Contact(BaseModel):
    id: str

    phone_number: Annotated[str, pydantic.Field(alias="phoneNumber")]
    r"""E.164 phone number."""

    country_code: Annotated[Optional[str], pydantic.Field(alias="countryCode")] = None

    whatsapp_window_open: Annotated[
        Optional[bool], pydantic.Field(alias="whatsappWindowOpen")
    ] = None
    r"""Whether the 24-hour WhatsApp window is currently open."""

    last_whatsapp_message_at: Annotated[
        Optional[datetime], pydantic.Field(alias="lastWhatsappMessageAt")
    ] = None
    r"""When the contact last messaged via WhatsApp."""

    metadata: Optional[Dict[str, str]] = None

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
