"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class ContactUpdateRequestTypedDict(TypedDict):
    metadata: NotRequired[Dict[str, str]]


class ContactUpdateRequest(BaseModel):
    metadata: Optional[Dict[str, str]] = None
