"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from zavu_sdk.types import BaseModel
from zavu_sdk.utils import FieldMetadata, PathParamMetadata


class GetContactByPhoneRequestTypedDict(TypedDict):
    phone_number: str
    r"""E.164 phone number."""


class GetContactByPhoneRequest(BaseModel):
    phone_number: Annotated[
        str,
        pydantic.Field(alias="phoneNumber"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""E.164 phone number."""
