"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from zavu_sdk.types import BaseModel
from zavu_sdk.utils import FieldMetadata, PathParamMetadata


class GetMessageRequestTypedDict(TypedDict):
    message_id: str


class GetMessageRequest(BaseModel):
    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
