"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sender import Sender, SenderTypedDict
from typing import List
from typing_extensions import TypedDict
from zavu_sdk.types import BaseModel


class ListSendersResponseTypedDict(TypedDict):
    r"""List of sender profiles."""

    items: List[SenderTypedDict]


class ListSendersResponse(BaseModel):
    r"""List of sender profiles."""

    items: List[Sender]
