"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .template import Template, TemplateTypedDict
from typing import List
from typing_extensions import TypedDict
from zavu_sdk.types import BaseModel


class ListTemplatesResponseTypedDict(TypedDict):
    r"""List of templates."""

    items: List[TemplateTypedDict]


class ListTemplatesResponse(BaseModel):
    r"""List of templates."""

    items: List[Template]
