"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channel import Channel
from .message import Message, MessageTypedDict
from .messagestatus import MessageStatus
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from zavu_sdk.utils import FieldMetadata, QueryParamMetadata


class ListMessagesRequestTypedDict(TypedDict):
    status: NotRequired[MessageStatus]
    to: NotRequired[str]
    channel: NotRequired[Channel]
    r"""Delivery channel."""
    limit: NotRequired[int]
    cursor: NotRequired[str]


class ListMessagesRequest(BaseModel):
    status: Annotated[
        Optional[MessageStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    to: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    channel: Annotated[
        Optional[Channel],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Delivery channel."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


class ListMessagesResponseTypedDict(TypedDict):
    r"""List of messages."""

    items: List[MessageTypedDict]
    next_cursor: NotRequired[Nullable[str]]


class ListMessagesResponse(BaseModel):
    r"""List of messages."""

    items: List[Message]

    next_cursor: Annotated[
        OptionalNullable[str], pydantic.Field(alias="nextCursor")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["nextCursor"]
        nullable_fields = ["nextCursor"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
