"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class MessageContentContactTypedDict(TypedDict):
    name: NotRequired[str]
    phones: NotRequired[List[str]]


class MessageContentContact(BaseModel):
    name: Optional[str] = None

    phones: Optional[List[str]] = None


class ButtonTypedDict(TypedDict):
    id: str
    title: str


class Button(BaseModel):
    id: str

    title: str


class RowTypedDict(TypedDict):
    id: str
    title: str
    description: NotRequired[str]


class Row(BaseModel):
    id: str

    title: str

    description: Optional[str] = None


class SectionTypedDict(TypedDict):
    title: str
    rows: List[RowTypedDict]


class Section(BaseModel):
    title: str

    rows: List[Row]


class MessageContentTypedDict(TypedDict):
    r"""Content for non-text message types (WhatsApp only)."""

    media_url: NotRequired[str]
    r"""URL of the media file (for image, video, audio, document, sticker)."""
    media_id: NotRequired[str]
    r"""WhatsApp media ID if already uploaded."""
    mime_type: NotRequired[str]
    r"""MIME type of the media."""
    filename: NotRequired[str]
    r"""Filename for documents."""
    latitude: NotRequired[float]
    r"""Latitude for location messages."""
    longitude: NotRequired[float]
    r"""Longitude for location messages."""
    location_name: NotRequired[str]
    r"""Name of the location."""
    location_address: NotRequired[str]
    r"""Address of the location."""
    contacts: NotRequired[List[MessageContentContactTypedDict]]
    r"""Contact cards for contact messages."""
    buttons: NotRequired[List[ButtonTypedDict]]
    r"""Interactive buttons (max 3)."""
    list_button: NotRequired[str]
    r"""Button text for list messages."""
    sections: NotRequired[List[SectionTypedDict]]
    r"""Sections for list messages."""
    emoji: NotRequired[str]
    r"""Emoji for reaction messages."""
    react_to_message_id: NotRequired[str]
    r"""Message ID to react to."""
    template_id: NotRequired[str]
    r"""Template ID for template messages."""
    template_variables: NotRequired[Dict[str, str]]
    r"""Variables for template rendering. Keys are variable positions (1, 2, 3...)."""


class MessageContent(BaseModel):
    r"""Content for non-text message types (WhatsApp only)."""

    media_url: Annotated[Optional[str], pydantic.Field(alias="mediaUrl")] = None
    r"""URL of the media file (for image, video, audio, document, sticker)."""

    media_id: Annotated[Optional[str], pydantic.Field(alias="mediaId")] = None
    r"""WhatsApp media ID if already uploaded."""

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None
    r"""MIME type of the media."""

    filename: Optional[str] = None
    r"""Filename for documents."""

    latitude: Optional[float] = None
    r"""Latitude for location messages."""

    longitude: Optional[float] = None
    r"""Longitude for location messages."""

    location_name: Annotated[Optional[str], pydantic.Field(alias="locationName")] = None
    r"""Name of the location."""

    location_address: Annotated[
        Optional[str], pydantic.Field(alias="locationAddress")
    ] = None
    r"""Address of the location."""

    contacts: Optional[List[MessageContentContact]] = None
    r"""Contact cards for contact messages."""

    buttons: Optional[List[Button]] = None
    r"""Interactive buttons (max 3)."""

    list_button: Annotated[Optional[str], pydantic.Field(alias="listButton")] = None
    r"""Button text for list messages."""

    sections: Optional[List[Section]] = None
    r"""Sections for list messages."""

    emoji: Optional[str] = None
    r"""Emoji for reaction messages."""

    react_to_message_id: Annotated[
        Optional[str], pydantic.Field(alias="reactToMessageId")
    ] = None
    r"""Message ID to react to."""

    template_id: Annotated[Optional[str], pydantic.Field(alias="templateId")] = None
    r"""Template ID for template messages."""

    template_variables: Annotated[
        Optional[Dict[str, str]], pydantic.Field(alias="templateVariables")
    ] = None
    r"""Variables for template rendering. Keys are variable positions (1, 2, 3...)."""
