"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


MessageType = Literal[
    "text",
    "image",
    "video",
    "audio",
    "document",
    "sticker",
    "location",
    "contact",
    "buttons",
    "list",
    "reaction",
    "template",
]
r"""Type of message. Non-text types are WhatsApp only."""
