"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channel import Channel
from .messagecontent import MessageContent, MessageContentTypedDict
from .messagetype import MessageType
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class MessageRequestTypedDict(TypedDict):
    r"""Request body to send a message."""

    to: str
    r"""Recipient phone number in E.164 format."""
    channel: NotRequired[Channel]
    r"""Delivery channel."""
    message_type: NotRequired[MessageType]
    r"""Type of message. Non-text types are WhatsApp only."""
    text: NotRequired[str]
    r"""Text body for text messages or caption for media messages."""
    content: NotRequired[MessageContentTypedDict]
    r"""Content for non-text message types (WhatsApp only)."""
    idempotency_key: NotRequired[str]
    r"""Optional idempotency key to avoid duplicate sends."""
    metadata: NotRequired[Dict[str, str]]
    r"""Arbitrary metadata to associate with the message."""


class MessageRequest(BaseModel):
    r"""Request body to send a message."""

    to: str
    r"""Recipient phone number in E.164 format."""

    channel: Optional[Channel] = None
    r"""Delivery channel."""

    message_type: Annotated[
        Optional[MessageType], pydantic.Field(alias="messageType")
    ] = None
    r"""Type of message. Non-text types are WhatsApp only."""

    text: Optional[str] = None
    r"""Text body for text messages or caption for media messages."""

    content: Optional[MessageContent] = None
    r"""Content for non-text message types (WhatsApp only)."""

    idempotency_key: Annotated[
        Optional[str], pydantic.Field(alias="idempotencyKey")
    ] = None
    r"""Optional idempotency key to avoid duplicate sends."""

    metadata: Optional[Dict[str, str]] = None
    r"""Arbitrary metadata to associate with the message."""
