"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .message import Message, MessageTypedDict
from typing_extensions import TypedDict
from zavu_sdk.types import BaseModel


class MessageResponseTypedDict(TypedDict):
    message: MessageTypedDict


class MessageResponse(BaseModel):
    message: Message
