"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channel import Channel
from .messagecontent import MessageContent, MessageContentTypedDict
from .messagestatus import MessageStatus
from .messagetype import MessageType
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class MessageTypedDict(TypedDict):
    id: str
    to: str
    channel: Channel
    r"""Delivery channel."""
    message_type: MessageType
    r"""Type of message. Non-text types are WhatsApp only."""
    status: MessageStatus
    created_at: datetime
    from_: NotRequired[str]
    sender_id: NotRequired[str]
    text: NotRequired[str]
    r"""Text content or caption."""
    content: NotRequired[MessageContentTypedDict]
    r"""Content for non-text message types (WhatsApp only)."""
    provider_message_id: NotRequired[str]
    r"""Message ID from the delivery provider."""
    error_code: NotRequired[Nullable[str]]
    error_message: NotRequired[Nullable[str]]
    metadata: NotRequired[Dict[str, str]]
    updated_at: NotRequired[datetime]


class Message(BaseModel):
    id: str

    to: str

    channel: Channel
    r"""Delivery channel."""

    message_type: Annotated[MessageType, pydantic.Field(alias="messageType")]
    r"""Type of message. Non-text types are WhatsApp only."""

    status: MessageStatus

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    from_: Annotated[Optional[str], pydantic.Field(alias="from")] = None

    sender_id: Annotated[Optional[str], pydantic.Field(alias="senderId")] = None

    text: Optional[str] = None
    r"""Text content or caption."""

    content: Optional[MessageContent] = None
    r"""Content for non-text message types (WhatsApp only)."""

    provider_message_id: Annotated[
        Optional[str], pydantic.Field(alias="providerMessageId")
    ] = None
    r"""Message ID from the delivery provider."""

    error_code: Annotated[OptionalNullable[str], pydantic.Field(alias="errorCode")] = (
        UNSET
    )

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET

    metadata: Optional[Dict[str, str]] = None

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "from",
            "senderId",
            "text",
            "content",
            "providerMessageId",
            "errorCode",
            "errorMessage",
            "metadata",
            "updatedAt",
        ]
        nullable_fields = ["errorCode", "errorMessage"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
