"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from zavu_sdk.types import BaseModel


class PhoneIntrospectionRequestTypedDict(TypedDict):
    phone_number: str


class PhoneIntrospectionRequest(BaseModel):
    phone_number: Annotated[str, pydantic.Field(alias="phoneNumber")]
