"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class PhoneIntrospectionResponseTypedDict(TypedDict):
    phone_number: str
    country_code: str
    valid_number: bool
    whatsapp_window_open: NotRequired[bool]
    r"""Whether a 24h WhatsApp window is open for this number."""


class PhoneIntrospectionResponse(BaseModel):
    phone_number: Annotated[str, pydantic.Field(alias="phoneNumber")]

    country_code: Annotated[str, pydantic.Field(alias="countryCode")]

    valid_number: Annotated[bool, pydantic.Field(alias="validNumber")]

    whatsapp_window_open: Annotated[
        Optional[bool], pydantic.Field(alias="whatsappWindowOpen")
    ] = None
    r"""Whether a 24h WhatsApp window is open for this number."""
