"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .reactionrequest import ReactionRequest, ReactionRequestTypedDict
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel
from zavu_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class SendReactionRequestTypedDict(TypedDict):
    message_id: str
    body: ReactionRequestTypedDict
    zavu_sender: NotRequired[str]
    r"""Optional sender profile ID. If omitted, the project's default sender will be used."""


class SendReactionRequest(BaseModel):
    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        ReactionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    zavu_sender: Annotated[
        Optional[str],
        pydantic.Field(alias="Zavu-Sender"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Optional sender profile ID. If omitted, the project's default sender will be used."""
