"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class SenderCreateRequestTypedDict(TypedDict):
    name: str
    phone_number: str
    set_as_default: NotRequired[bool]


class SenderCreateRequest(BaseModel):
    name: str

    phone_number: Annotated[str, pydantic.Field(alias="phoneNumber")]

    set_as_default: Annotated[Optional[bool], pydantic.Field(alias="setAsDefault")] = (
        False
    )
