"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagerequest import MessageRequest, MessageRequestTypedDict
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel
from zavu_sdk.utils import FieldMetadata, HeaderMetadata, RequestMetadata


class SendMessageRequestTypedDict(TypedDict):
    body: MessageRequestTypedDict
    zavu_sender: NotRequired[str]
    r"""Optional sender profile ID. If omitted, the project's default sender will be used."""


class SendMessageRequest(BaseModel):
    body: Annotated[
        MessageRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    zavu_sender: Annotated[
        Optional[str],
        pydantic.Field(alias="Zavu-Sender"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Optional sender profile ID. If omitted, the project's default sender will be used."""
