"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class CapabilitiesTypedDict(TypedDict):
    sms: NotRequired[bool]
    r"""Whether SMS is enabled for this sender."""
    whatsapp: NotRequired[bool]
    r"""Whether WhatsApp is enabled for this sender."""


class Capabilities(BaseModel):
    sms: Optional[bool] = None
    r"""Whether SMS is enabled for this sender."""

    whatsapp: Optional[bool] = None
    r"""Whether WhatsApp is enabled for this sender."""


class SenderTypedDict(TypedDict):
    id: str
    name: str
    phone_number: str
    r"""Phone number in E.164 format."""
    is_default: NotRequired[bool]
    r"""Whether this sender is the project's default."""
    capabilities: NotRequired[CapabilitiesTypedDict]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class Sender(BaseModel):
    id: str

    name: str

    phone_number: Annotated[str, pydantic.Field(alias="phoneNumber")]
    r"""Phone number in E.164 format."""

    is_default: Annotated[Optional[bool], pydantic.Field(alias="isDefault")] = False
    r"""Whether this sender is the project's default."""

    capabilities: Optional[Capabilities] = None

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
