"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .whatsappcategory import WhatsAppCategory
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


class TemplateCreateRequestTypedDict(TypedDict):
    name: str
    body: str
    language: NotRequired[str]
    whatsapp_category: NotRequired[WhatsAppCategory]
    r"""WhatsApp template category."""
    variables: NotRequired[List[str]]


class TemplateCreateRequest(BaseModel):
    name: str

    body: str

    language: Optional[str] = "en"

    whatsapp_category: Annotated[
        Optional[WhatsAppCategory], pydantic.Field(alias="whatsappCategory")
    ] = None
    r"""WhatsApp template category."""

    variables: Optional[List[str]] = None
