"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .whatsappcategory import WhatsAppCategory
from datetime import datetime
import pydantic
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zavu_sdk.types import BaseModel


Status = Literal[
    "pending",
    "approved",
    "rejected",
]


class TemplateTypedDict(TypedDict):
    id: str
    name: str
    r"""Template name (must match WhatsApp template name)."""
    language: str
    r"""Language code."""
    body: str
    r"""Template body with variables: {{1}}, {{2}}, etc."""
    category: WhatsAppCategory
    r"""WhatsApp template category."""
    status: NotRequired[Status]
    variables: NotRequired[List[str]]
    r"""List of variable names for documentation."""
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class Template(BaseModel):
    id: str

    name: str
    r"""Template name (must match WhatsApp template name)."""

    language: str
    r"""Language code."""

    body: str
    r"""Template body with variables: {{1}}, {{2}}, etc."""

    category: WhatsAppCategory
    r"""WhatsApp template category."""

    status: Optional[Status] = "pending"

    variables: Optional[List[str]] = None
    r"""List of variable names for documentation."""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
