"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .senderupdaterequest import SenderUpdateRequest, SenderUpdateRequestTypedDict
import pydantic
from typing_extensions import Annotated, TypedDict
from zavu_sdk.types import BaseModel
from zavu_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateSenderRequestTypedDict(TypedDict):
    sender_id: str
    body: SenderUpdateRequestTypedDict


class UpdateSenderRequest(BaseModel):
    sender_id: Annotated[
        str,
        pydantic.Field(alias="senderId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        SenderUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
