"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contactupdaterequest import ContactUpdateRequest, ContactUpdateRequestTypedDict
import pydantic
from typing_extensions import Annotated, TypedDict
from zavu_sdk.types import BaseModel
from zavu_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateContactRequestTypedDict(TypedDict):
    contact_id: str
    body: ContactUpdateRequestTypedDict


class UpdateContactRequest(BaseModel):
    contact_id: Annotated[
        str,
        pydantic.Field(alias="contactId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        ContactUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
