"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


WhatsAppCategory = Literal[
    "UTILITY",
    "MARKETING",
    "AUTHENTICATION",
]
r"""WhatsApp template category."""
